---
title: "Reproducible Pitch"
author: "Sai Gayathri J S"
date: '2022-03-19'
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

## Regression models

URL: https://github.com/SaiGayathri0909/Developing-Data-Products/tree/main/WEEK%204%20Assignments

## Details
You can find all the details here
URL: https://github.com/SaiGayathri0909/Developing-Data-Products/tree/main/WEEK%204%20Assignments/Shiny%20Ap
## mtcars dataset

The data used was mtcars, which comes installed in R
---
## Data Set used
```{r}
library(datasets)
head(mtcars, 3)
```

---

## Analysis  - Main code
```r
  formulaTextPoint <- reactive({
    paste("mpg ~", "as.integer(", input$variable, ")")  })
  
  fit <- reactive({
    lm(as.formula(formulaTextPoint()), data=mpgData)  })
  ...
  output$fit <- renderPrint({
    summary(fit()) })
  
  output$mpgPlot <- renderPlot({
    with(mpgData, {
      plot(as.formula(formulaTextPoint()))
      abline(fit(), col=2)
    })  })
```
